sudo: required
dist: trusty

jobs:
 include:
      
    - stage: backend
      name: "backend tests"
      language: java
      jdk: oraclejdk13    
      before_script:
        - cd BackEnd/MusicBoard/
        - chmod +x mvnw
      script:
        - ./mvnw test
        
    - stage: backend
      name: "backend test and build"
      language: java
      jdk: oraclejdk13
      env:
        global:
          - CC_TEST_REPORTER_ID=51ba226f3e020a5d3f0e69b5a968fb358d2f2514f1c094d6080c58d422087bcd
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - cd BackEnd/MusicBoard/
        - chmod +x mvnw
      script:
        - ./mvnw install
      after_script:
        - cd ..
        - ./cc-test-reporter format-coverage -d -t jacoco ./BackEnd/MusicBoard/target/jacoco-ut/jacoco.xml
        - ./cc-test-reporter upload-coverage -d -r 51ba226f3e020a5d3f0e69b5a968fb358d2f2514f1c094d6080c58d422087bcd

 notifications:
  email: false
